### ISSUE TITLE
Get rid of all this environment variable bullhooey

### ISSUE THREAD

**Issue by eddieantonio** [orezpraw/unnaturalcode#13]
Having to export all these environment variables is darn irksome:

``` sh
export ESTIMATENGRAM
export TEST_FILE_LIST
export LD_LIBRARY_PATH
export VIRTUALENV_ACTIVATE
# WHYYYYYYYYYYY?
```

---
- [ ] `ESTIMATENGRAM` should be obsolete soon, see #12
- [ ] `LD_LIBRARY_PATH` same as above
- [x] `TEST_FILE_LIST` is.. not actually needed anymore, since it can just rely on the test corpus (#6) 
- [ ] `VIRTUALENV_ACTIVATE` This is misleading. It's the virtualenv of the project we're siccing unnaturalcode at... I think. I'm not sure if this is strictly necessary, if the virtualenv of the project is already activated. It might be possible to determine this automatically (see #14)
